### ISSUE TITLE
Cannot build successfully with yarn

### ISSUE THREAD

**Issue by dieface** [mikesteele/dc2#4]
![image](https://user-images.githubusercontent.com/2155132/53812715-03ed3680-3f97-11e9-9a84-7dc746bc6ff9.png)

**Comment by mikesteele** [comment]
Well that's embarrassing haha, sorry about that 😅 (that's my old
employer's package manager)

It should build if you remove `yarn.lock`.

I haven't documented this yet but to use this repo with the v1 popup, use
https://github.com/mikesteele/dc2-build and follow the instructions in the
README there. You'll probably need to remove `yarn.lock` inside of
`injected-bundle` to be able to build it. Once it's built, load the `build`
directory in Chrome.

**Comment by mikesteele** [comment]
Let me know if you have any questions on dc2-build to work!
